version: 2.1

# 社内orbができるまでインライン利用
orbs:
  codecov: codecov/codecov@1.1.1

# 共通化部分
# 実行環境
executors:
  node:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12

  go:
    working_directory: ~/workspace
    docker:
      - image: circleci/golang:1.16.0

jobs:
  setup:
    executor:
      name: node
    steps:
      # git pullする
      - checkout
      - run: npm install
      # jobを超えて使いまわしたものをroot/pathsに保存する
      - persist_to_workspace:
          root: .
          paths:
          - 'node_modules'
  test:
    executor:
      name: node
    steps:
      - checkout
       # persist_to_workspaceで保存したデータをatのパスにダウンロードする
      - attach_workspace:
          at: .

      - run:
          name: "JavaScript Test Suite"
          command: npx jest --ci --runInBand --reporters=default --reporters=jest-junit --detectOpenHandles
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/

      - codecov/upload:
          file: ./coverage/lcov.info

      - store_test_results:
          path: ./reports/junit/

  release:
    executor:
      name: go
    steps:
      - checkout
      - run:
          name: Install ghch and github-release
          command: |
            go get github.com/Songmu/ghch/cmd/ghch@v0.10.2
            go get github.com/github-release/github-release@v0.10.0
      - attach_workspace:
          at: .
      - run:
          name: Echo version
          command: echo ${CIRCLE_TAG}
      - run:
          name: Echo pipeline
          command: echo << pipeline.git.tag >>
      - run:
          name: Echo Branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: ghch
          command: ghch --format=markdown --latest
      # - run:
      #     name: Create release note
      #     command: |
      #     github-release release \
      #       --tag "${CIRCLE_TAG}" \
      #       --name "${CIRCLE_BRANCH}" \
      #       --description "$(ghch --format=markdown --latest)"

workflows:
  setup_and_deploy:
    jobs:
      - setup
      - test:
          # 以下のjobの完了後に実行する
          requires:
            - setup
      - release:
          requires:
            - setup
            - test
